export const ERROR_STATUS_CODE = {
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  INVALID_RESPONSE: "INVALID_RESPONSE",
  EXCEPTION: "EXCEPTION",
} as const;
