#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

if ! echo "$COMMIT_MSG" | grep -qE '\(.*\)(:|\s).+'; then
  printf "================= \n"
  printf "Invalid commit message format.\n"
  printf "💡 Commit messages should follow the conventional format:\n"
  printf "   (type): description\n"
  printf "   Example: (feat): add user authentication\n\n"
  printf "🐇 To create a properly formatted commit message, use the following command:\n"
  printf "   \033[34mnpx cz\033[0m\n"
  printf "================= \n"
  exit 1
fi

exit 0
